
# all
# GET http://localhost:3000/todos

# one
GET http://localhost:3000/todos/30

# save
# POST http://localhost:3000/todos
# Content-Type: application/json

# {
#   "title": "task3",
#   "description": "learn english",
#   "completed": false
# }

# update
PUT http://localhost:3000/todos/30
Content-Type: application/json

{
  "title": "task5",
  "description": "learn english",
  "completed": false
}

# DELETE  http://localhost:3000/todos/27